---

# Dynamic Pipeline
# This pipeline should not be set from terminal; it is scaffolded and updated via ./boostrap.yml.
#
# 2 types of variable substitutions are used here:
# 
# - ( ( vault-variable ) ): static, unchanging, global variables
# - { { local-variable } }: dynamic branch- or pipe-specific variables
# 
# Local variables should only be used in non-secure areas, like a branch name.
# Local variables should not be tokens, keys, passwords, etc.

resources:
###
# Github, Release, and Pull Request resources
###
- name: repo
  type: git
  source:
    uri: https://((github-access-token))@github.com/limbicmedia/concourse-dynamic-pipe-test.git

- name: git-pr
  type: pull-request
  check_every: 24h
  webhook_token: ((github-access-token))
  source:
    repository: limbicmedia/concourse-dynamic-pipe-test
    access_token: ((github-access-token))

###
# Docker images
###
- name: alpine-node
  type: docker-image
  source:
    repository: mhart/alpine-node
    tag: latest

###
# Concourse pipeline resources
###

jobs:
- name: test
  plan:
  - get: repo
    trigger: false
  - get: alpine-node
    params: {save: true}
  - task: echo-changes
    params:
      skip_download: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: mhart/alpine-node
          tag: latest
      inputs:
        - name: repo
      run:
        path: sh
        args:
          - -exc
          - |
            find .
            cat repo/CHANGES.md

